version: "3.8"
services:
  react-app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - 3000:3000 # Typical port used for React development
    environment:
      - NODE_ENV=development
    volumes:
      - .:/app
      - /app/node_modules
    command: npm start # Override the default command to use the development server

networks:
  app_network:
    external: true
