version: "3.8"
services:
  react-app:
    container_name: portfolio-react-app
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - "8080:80"
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
