version: "3.8"
services:
  react-app:
    build:
      context: .
      dockerfile: Dockerfile.aws
    ports:
      - "8080:80"
      - "443:443"
    environment:
      - TUNNEL_TOKEN=eyJhIjoiNjdjZTAxMDRiOWY4YjAxMzhiMWVhMWRlNDhhOGViNGQiLCJ0IjoiODBkZjVkMTgtYWFhNy00ZDc4LWE1MTAtODc5MTRjZDNjNjNkIiwicyI6IlptVTJZMkptT1dZdFpqQXhaQzAwTVdRMExXRXdOVGd0Wm1abVlUZ3dZV1pqT1dObSJ9
      - NO_AUTOUPDATE=true
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./certificates:/etc/nginx/certificates
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
