version: "3.8"
services:
  react-app:
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - "8008:8008"
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
