version: "3.8"
services:
  react-app:
    container_name: portfolio
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - "8008:80" # Expose port 80 for production
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
